vulkcan: Update SRC_URI to use main branch
The upstream repository has renamed the master branch to main. This
causes fetch errors like:

ERROR: vulkan-loader-1.2.182.0-r0 do_fetch: Fetcher failure: Unable to find revision 1896143df69d439b0933c1bb485f5a4587bdf2dc in branch master even from upstream
ERROR: vulkan-loader-1.2.182.0-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/KhronosGroup/Vulkan-Loader.git;protocol=https;branch=master')

Fix it by adding a bbappend replacing 'master' with 'main' in SRC_URI.

Signed-off-by: Nate Drude <nate.d@variscite.com>