variscite: scripts: mx6ul_mx7_install_yocto: Move Wi-Fi module detection to SoC level
Since the VAR-SOM-MX7 does not have the new Wi-Fi module. Move the detect_wifi_module
function to the SoC level, so it will only run for the i.MX6UL* based SoMs.

This fix the error message when using the install_yocto.sh:

*** Variscite MX6UL/MX6ULL/MX6ULZ/MX7 Yocto eMMC/NAND Recovery ***

Error: Read failed
Board: VAR-SOM-MX7
Installing to internal storage device: NAND

Signed-off-by: Diego Dorta <diego.d@variscite.com>