mx6ul_mx7_install_yocto: Limit Wi-Fi module detection to DART-6UL
Run detect_wifi_module only for DART-6UL to determine if the SOM
has Laird or Murate Wi-Fi/BT chipset.

This keeps Wi-Fi detection and validation scoped to the relevant SOMs
and avoids unconditional detection tries.

Fixes 'Error: read failed' when invoking for VAR-SOM-MX7:

root@imx7-var-som:~# install_yocto.sh
*** Variscite MX6UL/MX6ULL/MX6ULZ/MX7 Yocto eMMC/NAND Recovery ***

Error: Read failed
[...]

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>
(cherry picked from commit b6343ed238a75539166da21eaeb0ccb07e0c0295)