python3-pillow: add tk to RDEPENDS ptest pkg only if x11 in DISTRO_FEATURES
The commit openembedded/meta-openembedded@ffe9a543e1c4 added tk to
RDEPENDS:${PN}-ptest. Which cause this error on non x11 builds:

    ERROR: Nothing RPROVIDES 'tk' (but meta-openembedded/meta-python/recipes-devtools/python/python3-pillow_9.4.0.bb
           RDEPENDS on or otherwise requires it) tk was skipped: missing required
           distro feature 'x11' (not in DISTRO_FEATURES)
    NOTE: Runtime target 'tk' is unbuildable, removing...
          Missing or unbuildable dependency chain was: ['tk']
    NOTE: Runtime target 'python3-pillow' is unbuildable, removing...
          Missing or unbuildable dependency chain was: ['python3-pillow', 'tk']
    NOTE: Runtime target 'torchvision' is unbuildable, removing...
          Missing or unbuildable dependency chain was: ['torchvision', 'python3-pillow', 'tk']
    NOTE: Runtime target 'packagegroup-var-ml' is unbuildable, removing...
          Missing or unbuildable dependency chain was: ['packagegroup-var-ml', 'torchvision', 'python3-pillow', 'tk']
    ERROR: Required build target 'fsl-image-gui' has no buildable providers.
          Missing or unbuildable dependency chain was: ['fsl-image-gui', 'packagegroup-var-ml', 'torchvision', 'python3-pillow', 'tk']

Add tk dependency only if DISTRO_FEATURES includes x11.

Derived from openembedded/meta-openembedded@6e8c90560e0a.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>