add missing wayland backend
Fixed the following compilation error:
  ERROR: .../sources/meta-qt6/recipes-qt/qt6/qtbase_git.bb: Unable to get checksum for nativesdk-qtbase SRC_URI entry qt-wayland.sh: file could not be found

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>