wxwidgets_3.2.0.bbappend: fix conflict error on DISTRO=fsl-framebuffer
ERROR: .../meta-variscite-sdk/recipes-extended/wxwidgets/wxwidgets_3.2.0.bb: wxwidgets: PACKAGECONFIG[gtk] Invalid conflict package config 'no_gui' specified.
ERROR: .../meta-variscite-sdk/recipes-extended/wxwidgets/wxwidgets_3.2.0.bb: wxwidgets: PACKAGECONFIG[libsecret] Invalid conflict package config 'no_gui' specified.
ERROR: .../meta-variscite-sdk/recipes-extended/wxwidgets/wxwidgets_3.2.0.bb: wxwidgets: PACKAGECONFIG[qt] Invalid conflict package config 'no_gui' specified.
ERROR: .../meta-variscite-sdk/recipes-extended/wxwidgets/wxwidgets_3.2.0.bb: wxwidgets: PACKAGECONFIG[webkit] Invalid conflict package config 'no_gui' specified.
ERROR: .../meta-variscite-sdk/recipes-extended/wxwidgets/wxwidgets_3.2.0.bb: wxwidgets: PACKAGECONFIG[webkit] Conflict package config 'no_gui' set in PACKAGECONFIG.
ERROR: Parsing halted due to errors, see error messages above

Signed-off-by: Masaru Tsuchiyama <m.tmatma@gmail.com>