var-install-android: add parted-native to DEPENDS
wic commands require parted-native to be installed.
var-host-docker-containers does not have parted installed, resulting
in the following error:

Fixes:
ERROR: Can't find executable parted

Signed-off-by: Nate Drude <nate.d@variscite.com>